# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert=""
  tls_key=""
  ca_cert=""

  region="AU915"
  frequency_min=915000000
  frequency_max=928000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      920000000,
      920200000,
      920400000,
      920600000,
      920800000,
      921000000,
      921200000,
      921400000,
    ]
  
    [backend.basic_station.concentrators.lora_std]
    frequency=920700000
    bandwidth=500000  
    spreading_factor=8
