# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert=""
  tls_key=""
  ca_cert=""

  region="AU915"
  frequency_min=915000000
  frequency_max=928000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      918400000,
      918600000,
      918800000,
      919000000,
      919200000,
      919400000,
      919600000,
      919800000,
    ]
  
    [backend.basic_station.concentrators.lora_std]
    frequency=919100000
    bandwidth=500000  
    spreading_factor=8
