# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[backend]
type="basic_station"

  [backend.basic_station]
  bind=":3001"
  tls_cert=""
  tls_key=""
  ca_cert=""

  region="US915"
  frequency_min=923000000
  frequency_max=928000000


  [[backend.basic_station.concentrators]]

    [backend.basic_station.concentrators.multi_sf]
    frequencies=[
      908700000,
      908900000,
      909100000,
      909300000,
      909500000,
      909700000,
      909900000,
      910100000,
    ]
  
    [backend.basic_station.concentrators.lora_std]
    frequency=909400000
    bandwidth=500000  
    spreading_factor=8
