version: "3"

services:
  loraserver:
    image: loraserver/loraserver:3
    environment:
      - POSTGRESQL.DSN=postgres://loraserver_ns:loraserver_ns@postgresql/loraserver_ns?sslmode=disable
      - REDIS.URL=redis://redis:6379
      - NETWORK_SERVER.BAND.NAME=EU_863_870
      - NETWORK_SERVER.GATEWAY.BACKEND.MQTT.SERVER=tcp://mosquitto:1883
      - JOIN_SERVER.DEFAULT.SERVER=http://appserver:8003
      - GEOLOCATION_SERVER.SERVER=geoserver:8005

  appserver:
    image: loraserver/lora-app-server:3
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL.DSN=postgres://loraserver_as:loraserver_as@postgresql/loraserver_as?sslmode=disable
      - REDIS.URL=redis://redis:6379
      - APPLICATION_SERVER.INTEGRATION.MQTT.SERVER=tcp://mosquitto:1883
      - APPLICATION_SERVER.API.PUBLIC_HOST=appserver:8001
      - APPLICATION_SERVER.EXTERNAL_API.JWT_SECRET=verysecret

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:3
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION.MQTT.AUTH.GENERIC.SERVER=tcp://mosquitto:1883

  geoserver:
    image: loraserver/lora-geo-server:3
    environment:
      - GEO_SERVER.BACKEND.NAME=collos

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
