services:
  chirpstack:
    image: chirpstack/chirpstack:4
    hostname: ${CHIRPSTACK_HOSTNAME}
    command: -c /etc/chirpstack
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./rds-combined-ca-bundle.pem:/certs/rds-combined-ca-bundle.pem:ro
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - AWS__IOT__ENDPOINT=${AWS_IOT_ENDPOINT}
      - CHIRPSTACK__HOSTNAME=${CHIRPSTACK_HOSTNAME}
      - CHIRPSTACK__ENVIRONMENT=${CHIRPSTACK_ENVIRONMENT}
      - POSTGRESQL__DSN=${POSTGRES_DSN}
      - POSTGRESQL__CA__CERT=${POSTGRESQL_CA_CERT}
      - REDIS__SERVER=${REDIS_SERVER}
    ports:
      - "8080:8080"

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - CHIRPSTACK__HOSTNAME=${CHIRPSTACK_HOSTNAME}
      - CHIRPSTACK__ENVIRONMENT=${CHIRPSTACK_ENVIRONMENT} # or dev/prod; MUST exist for GB
      - INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883 # <- broker for GB
      - INTEGRATION__MQTT__CLIENT_ID=gb-${CHIRPSTACK_ENVIRONMENT}-${CHIRPSTACK_HOSTNAME}
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=${CHIRPSTACK_ENVIRONMENT}/us915_1/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=${CHIRPSTACK_ENVIRONMENT}/us915_1/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=$$share/${CHIRPSTACK_ENVIRONMENT}-gbgrp/${CHIRPSTACK_ENVIRONMENT}/us915_1/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto

  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    ports:
      - "3001:3001"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./configuration/mosquitto/config/:/mosquitto/config/
