version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=EU868
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://mosquitto:1883
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    depends_on:
      - postgresql
      - mosquitto

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
    depends_on: 
      - mosquitto

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root 
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
